baseURL = "https://example.com"
title = "Piper Williams | Blog"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "Naturally Curious"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "By Piper Williams" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Lead Threat & Vulnerability Analyst and Cyber Security Application tester. Previous Cloud Security Engineer. Software Development is my passion. Graphic Designing is my hobby. Welcome to my blog, my very own digital project diary with unique and engaging content. Explore my site and all that I have to offer; perhaps it will ignite your own passions as well."


    # Show the "built on Hugo" disclaimer
    showhugo = false

    # Urls for social networks
    linkedin = "https://www.linkedin.com/in/pswnr9/"
    github = "https://github.com/piper-sieren"
   

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false



[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"




